# Generated by Django 5.0.6 on 2024-08-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInspire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='roomInspireImages')),
            ],
        ),
    ]
