# Generated by Django 5.0.6 on 2024-08-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominspire',
            options={'verbose_name': 'Design', 'verbose_name_plural': 'Designs'},
        ),
        migrations.AlterModelTable(
            name='roominspire',
            table='design',
        ),
    ]
