# Generated by Django 5.0.6 on 2024-07-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='categories',
            table='categorty',
        ),
    ]
